stages:
  - clean
  - build
  - configure
  - apply_templates
  - test
  
image: ansible-viptela

variables:
  ANSIBLE_GATHERING: "smart"
  ANSIBLE_HOST_KEY_CHECKING: "false"
  ANSIBLE_RETRY_FILES_ENABLED: "false"
  ANSIBLE_ROLES_PATH: "./roles"
  ANSIBLE_SSH_PIPELINING: "true"
  ANSIBLE_LIBRARY: "./library"
  ANSIBLE_CONFIG: "./ansible.cfg"
  GIT_SUBMODULE_STRATEGY: "recursive"

clean:
  stage: clean
  script:
  - ansible-playbook clean.yml
  only:
    changes:
      - inventory/viptela-workshop.yml

build:
  stage: build
  script:
  - ansible-playbook build.yml

configure:
  stage: configure
  script:
  - ansible-playbook configure.yml
  - ansible-playbook import-templates.yml

apply_templates:
  stage: apply_templates
  script:
  - ansible-playbook waitfor-sync.yml
  - ansible-playbook attach-template.yml
 
test:
  stage: test
  script:
  - ansible-playbook check-sdwan.yml
