- name: Configure licensing
  hosts: firewall:&virl_hosts
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Deregister from smart account
      asa_command:
        commands:
          - "license smart deregister"
      ignore_errors: yes

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    session: "{{ lookup('env', 'VIRL_SESSION') | default('') }}"
  tasks:
    - block:
      - name: Check for session id file
        stat:
          path: "{{ virl_sim_file }}"
        register: stat_result

      - name: Get the existing session ID
        set_fact:
          session: "{{lookup('file', virl_sim_file) }}"
        when: stat_result.stat.exists
      when: session == ""

    - name: Delete cert dir
      file:
        path: "{{ viptela_cert_dir }}"
        state: absent

    - name: Remove host from known_hosts
      known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        state: absent
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups.all }}"

    - name: Destroy the simulation
      uri:
        url: "http://{{ virl_host }}:19399/simengine/rest/stop/{{ sim_id }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        method: GET
        return_content: yes
      no_log: false  # Don't show output as your password will be on the URI string
      register: uri_results
      failed_when: false
      delegate_to: localhost
      vars:
        sim_id: "{{ session | default(lookup('file', virl_sim_file, errors='ignore')) }}"

    - name: Delete Simulation ID File
      file:
        path: "{{ virl_sim_file }}"
        state: absent