- name: Check playbook reqiurements
  hosts: localhost
  tags:
    - control
    - edge
    - CA
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Check for the license file
      stat:
        path: "{{ serial_number_file }}"
      register: stat_result

    - assert:
        that:
          - stat_result.stat.exists
          - organization_name != ""
        msg: "'organization_name' must be defined and {{ serial_number_file }} must exist.  Verify the requirements in README are met."

- name: Check initial connectivity
  hosts: router:&virl_hosts
  tags:
    - check_control
    - check_all
    - control
    - edge
    - CA
  any_errors_fatal: true
  connection: network_cli
  gather_facts: no
  tasks:
    - ios_ping:
        dest: "{{ item }}"
        count: 60
      loop:
        - 10.0.1.10
        - 10.100.1.10
      tags:
        - initial

- name: Verify that vManage is fully operational
  hosts: localhost
  tags:
    - check_control
    - check_all
    - control
    - edge
    - CA
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Waiting for vManage API to start
      uri:
        url: "https://{{ hostvars['vmanage1'].ansible_host }}/dataservice/system/device/controllers"
        method: POST
        body:
          j_username: "{{ viptela_api_username }}"
          j_password: "{{ viptela_api_password }}"
        body_format: form-urlencoded
        return_content: yes
        validate_certs: no
      no_log: false
      register: uri_results
      delegate_to: localhost
      failed_when: false
      until: uri_results.msg.find("OK") != -1
      retries: 60
      delay: 10

- name: Create local CA
  hosts: localhost
  tags:
    - control
    - edge
    - CA
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Ensure directory exists for local self-signed TLS certs.
      file:
        path: "{{ viptela_cert_dir }}"
        state: directory

    - name: Generate an OpenSSL private key.
      openssl_privatekey:
        cipher: des3
        passphrase: "{{ viptela_CA_passphrase }}"
        path: "{{ viptela_cert_dir }}/myCA.key"

    - name: Generate an OpenSSL CSR.
      openssl_csr:
        path: "{{ viptela_cert_dir }}/myCA.csr"
        privatekey_path: "{{ viptela_cert_dir }}/myCA.key"
        privatekey_passphrase: "{{ viptela_CA_passphrase }}"
        common_name: viptelaCA.local

    - name: Generate a Self Signed OpenSSL certificate.
      openssl_certificate:
        path: "{{ viptela_cert_dir }}/myCA.pem"
        privatekey_path: "{{ viptela_cert_dir }}/myCA.key"
        privatekey_passphrase: "{{ viptela_CA_passphrase }}"
        csr_path: "{{ viptela_cert_dir }}/myCA.csr"
        provider: selfsigned

- name: Configuring Viptela components
  hosts: viptela_control:&virl_hosts
  tags:
    - control
    - edge
  any_errors_fatal: true
  connection: netconf
  gather_facts: no
  tasks:
    - name: Push NETCONF template
      netconf_config:
        content: "{{ lookup('template', 'viptela/netconf.j2') }}"

- name: Check connetivty to Viptela control plane
  hosts: router:&virl_hosts
  tags:
    - control
    - edge
    - check_control
    - check_all
  any_errors_fatal: true
  connection: network_cli
  gather_facts: no
  tasks:
    - ios_ping:
        dest: "{{ hostvars[item].vpn_instances[0].interfaces[0].ip.address | ipaddr('address') }}"
      loop: "{{ groups.viptela_control }}"

- name: Verify that vManage is fully operational
  hosts: localhost
  tags:
    - check_control
    - check_all
    - control
    - edge
    - CA
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Waiting for vManage API to start
      uri:
        url: "https://{{ hostvars['vmanage1'].ansible_host }}/dataservice/system/device/controllers"
        method: POST
        body:
          j_username: "{{ viptela_api_username }}"
          j_password: "{{ viptela_api_password }}"
        body_format: form-urlencoded
        return_content: yes
        validate_certs: no
      no_log: true
      register: uri_results
      delegate_to: localhost
      failed_when: false
      until: uri_results.msg.find("OK") != -1
      retries: 60
      delay: 10

- name: Configure vmanage
  hosts: localhost
  roles:
    - ansible-viptela
  tags:
    - control
    - edge
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host }}"

    - debug:
        msg: "vManage IP: {{ vmanage_ip }}"

    - name: Add vBond Hosts
      include_role:
        name: ansible-viptela
        tasks_from: add-controller
      vars:
        device_hostname: "{{ item }}"
        device_ip: "{{ hostvars[item].viptela.transport_ip }}"
        device_personality: vbond
      loop: "{{ groups.vbond_hosts }}"

    - name: Add vSmart Hosts
      include_role:
        name: ansible-viptela
        tasks_from: add-controller
      vars:
        device_hostname: "{{ item }}"
        device_ip: "{{ hostvars[item].viptela.transport_ip }}"
        device_personality: vsmart
      loop: "{{ groups.vsmart_hosts }}"

    - name: Set organization
      include_role:
        name: ansible-viptela
        tasks_from: set-org
      vars:
        org_name: "{{ organization_name }}"

    - set_fact:
        vbond_controller: "{{ groups.vbond_hosts[0] }}"

    - name: Set vBond
      include_role:
        name: ansible-viptela
        tasks_from: set-vbond
      vars:
        vbond_ip: "{{ hostvars[vbond_controller].viptela.transport_ip }}"

    - name: Set Enterprise Root CA
      include_role:
        name: ansible-viptela
        tasks_from: set-rootca
      vars:
        root_cert: "{{lookup('file', '{{ viptela_cert_dir }}/myCA.pem')}}"

    - name: Get Controler CSR
      include_role:
        name: ansible-viptela
        tasks_from: get-csr
      vars:
        device_ip: "{{ hostvars[item].viptela.transport_ip }}"
        device_hostname: "{{ item }}"
        csr_filename: "{{ viptela_cert_dir }}/{{ item }}.csr"
      loop: "{{ groups.viptela_control }}"

    - name: Sign Controller Cert
      openssl_certificate:
        csr_path: "{{ viptela_cert_dir }}/{{ item }}.csr"
        path: "{{ viptela_cert_dir }}/{{ item }}.crt"
        provider: ownca
        ownca_path: "{{ viptela_cert_dir }}/myCA.pem"
        ownca_privatekey_path: "{{ viptela_cert_dir }}/myCA.key"
        ownca_privatekey_passphrase: "{{ viptela_CA_passphrase }}"
      loop: "{{ groups.viptela_control }}"
      delegate_to: localhost

    - name: Install Controller Certificate
      include_role:
        name: ansible-viptela
        tasks_from: install-cert
      vars:
        device_cert: "{{lookup('file', '{{ viptela_cert_dir }}/{{ item }}.crt')}}"
      loop: "{{ groups.viptela_control }}"

    - name: Install Serial File
      vmanage_fileupload:
        host: "{{ vmanage_ip }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        file: "{{ serial_number_file }}"
      delegate_to: localhost

- name: Configuring Viptela components
  hosts: viptela_vedge:&virl_hosts
  tags:
    - edge
  any_errors_fatal: true
  connection: netconf
  gather_facts: no
  tasks:
    - name: Push NETCONF template
      netconf_config:
        content: "{{ lookup('template', 'viptela/netconf.j2') }}"

- name: Check connetivty to edges
  hosts: router:&virl_hosts
  tags:
    - edge
    - check_all
    - check_edge
  any_errors_fatal: true
  connection: network_cli
  gather_facts: no
  tasks:
    - ios_ping:
        dest: "{{ hostvars[item].vpn_instances[0].interfaces[0].ip.address | ipaddr('address') }}"
      loop: "{{ groups.viptela_vedge }}"

- name: Bootstrap vEdges
  hosts: viptela_vedge:&virl_hosts
  tags:
    - edge
  any_errors_fatal: true
  gather_facts: no
  serial: 1
  vars:
    viptela_api_username: admin
    viptela_api_password: admin
    viptela_cert_dir: "{{ lookup('env', 'PWD') }}/myCA"
    ansible_network_os: ios
  tasks:
    - set_fact:
        vmanage_host: "{{ groups.vmanage_hosts | first }}"

    - set_fact:
        vmanage_ip: "{{ hostvars[vmanage_host].ansible_host }}"

    - name: Bootstrap vEdge
      include_role:
        name: ansible-viptela
        tasks_from: bootstrap-vedge
      vars:
        device_ip: "{{ hostvars[item].ansible_host }}"
        root_ca_file: "{{ viptela_cert_dir }}/myCA.pem"

    - name: Do the thing
      uri:
        url: "https://{{ hostvars['vmanage1'].ansible_host }}/dataservice/system/device/sync/rootcertchain"
        method: GET
        headers:
          Cookie: "{{ viptela_api_cookie }}"
        validate_certs: no
        return_content: yes
      register: uri_results
      delegate_to: localhost

# - name: Checking connectivity between end hosts
#   hosts: client:&virl_hosts
#   tags:
#     - check_edge
#     - check_all
#     - edge
#   any_errors_fatal: true
#   gather_facts: no
#   tasks:
#     - wait_for:
#         port: 22
#         host: "{{ item }}"
#       loop:
#         - 10.0.1.10
# #        - 10.100.1.10
#       tags:
#         - configured